name: grisette-fused-effects
version: 0.1.0.0
synopsis: Support for fused-effects package with Grisette
description: Orphan instances and wrappers for fused-effects package with Grisette
category: Formal Methods, Theorem Provers, Symbolic Computation, SMT
author: "Sirui Lu"
maintainer: Sirui Lu (siruilu@cs.washington.edu)
license: BSD3
license-file: LICENSE
github: lsrcz/grisette-fused-effects
copyright: "2021-2022 Sirui Lu"

dependencies:
- base > 4.14 && < 5
- grisette-core == 0.1.0.0
- mtl >= 2.2.2
- transformers >= 0.5.6.2
- fused-effects >= 1.1.0.0

flags: {
  fast: {
    description: "Compile with O2 optimization",
    manual: False,
    default: True,
  }
}

when:
  - condition: flag(fast)
    then:
      ghc-options: -O2
    else:
      ghc-options: -O0

ghc-options: -Wall -ferror-spans

library:
  source-dirs: src

tests:
  spec:
    main: Main.hs
    source-dirs: test
    dependencies:
      - grisette-core
      - grisette-fused-effects
      - tasty >= 1.1.0.3
      - tasty-hunit >= 0.10
      - tasty-test-reporter >= 0.1.1.2
      - tasty-quickcheck >= 0.10.1
